import { fork, all } from "redux-saga/effects";

import { handleFriendRequest } from "../actions/ProfileActions";
import { loginSaga, OtpSaga, ResendOtpSaga, signUpSaga } from "./AuthSaga";
import {
  fetchNewsFeedSaga,
  fetchPattersSaga,
  fetchSinglePostSaga,
  postStatusSaga,
  commentDeletedSaga,
  deletePostSaga,
  editPostSaga,
  getTimelineSaga,
  updatePostSaga,
  postCommentSaga,
  fetchCommentsSaga,
  editCommentSaga,
  updateCommentSaga,
  fetchRepliesSaga,
  postReplySaga,
  editReplySaga,
  updateReplySaga,
  sharePostSaga,
  likeItemSaga,
  unLikeItemSaga,
  getVideosSaga,
  showGalleryPostSaga,
  getFriendRequestListSaga,
  getUserPhotosSaga,
  getUserAlbumsSaga,
  getUserVideosSaga,
  uploadUserAlbumSaga,
  uploadUserPhotoSaga,
  uploadUserVideoSaga,
  getUserAlbumMediaSaga,
} from "./NewsFeedSaga";
import {
  fetchCitiesSaga,
  fetchEduSaga,
  fetchExpSaga,
  fetchStatesSaga,
  sendSaveEduSaga,
  sendDeleteEducationSaga,
  sendDeleteExperienceSaga,
  sendSaveEmployementSaga,
  settingsSaga,
  updateProfSaga,
  educationUpdateSaga,
  experienceUpdateSaga,
  changePasswordSaga,
  createGroupSaga,
  handleFriendReqSaga,
  fetchBirthdayDataSaga,
  WishBirthdaySaga,
  deleteVideoSaga,
} from "./ProfileSaga";

import {
  walletSignUpSaga,
  walletSignInSaga,
  walletDataSaga,
  walletPreviewDataSaga,
  walletAddItemSaga,
  deleteWalletSaga,
  updateWalletItemSaga,
} from "./WalletSaga";

import {
  joinedRoomsSaga,
  myRoomsSaga,
  showRoomSaga,
  leaveRoomSaga,
  createRoomSaga,
  addMemberSaga,
  roomMembersSaga,
  fetchAlbumsDataSaga,
  deletePhotoSaga,
  getRoomsVideosSaga,
  updateRoomSaga,
  previewAlbumSaga,
  deleteAlbumSaga,
  deleteAlbumPhotoSaga,
  makeAdminSaga,
  removeAdminSaga,
  makeSilentObserverSaga,
  removeSilentObserverSaga,
  removeMemberSaga,
  uploadAlbumSaga,
  uploadAlbumImageSaga,
  uploadAlbumVideoSaga,
  deleteRoomRequestSaga,
} from "./RoomsSaga";

import {
  fetchReelsSaga,
  // fetchUserReelsSaga,
  uploadReelSaga,
  deleteReelSaga,
  updatedReelSaga,
  reactToggleSaga,
  increaseReelViewCountSaga,
  fetchReelsCommentsSaga,
} from "./ReelsSaga";

import {
  exploreBuyNsellReqSaga,
  parentCategoryBuyNsellReqSaga,
} from "./BuyNsellSaga";

export function* rootSaga() {
  yield all([
    loginSaga(),
    signUpSaga(),
    OtpSaga(),
    settingsSaga(),
    updateProfSaga(),
    fetchEduSaga(),
    sendSaveEduSaga(),
    sendDeleteEducationSaga(),
    sendDeleteExperienceSaga(),
    fetchExpSaga(),
    sendSaveEmployementSaga(),
    fetchNewsFeedSaga(),
    postStatusSaga(),
    commentDeletedSaga(),
    fetchPattersSaga(),
    fetchSinglePostSaga(),
    fetchStatesSaga(),
    fetchCitiesSaga(),
    deletePostSaga(),
    editPostSaga(),
    getTimelineSaga(),
    updatePostSaga(),
    educationUpdateSaga(),
    experienceUpdateSaga(),
    sendDeleteExperienceSaga(),
    sendDeleteEducationSaga(),
    fetchCommentsSaga(),
    postCommentSaga(),
    editCommentSaga(),
    updateCommentSaga(),
    fetchRepliesSaga(),
    postReplySaga(),
    editReplySaga(),
    updateReplySaga(),
    sharePostSaga(),
    changePasswordSaga(),
    likeItemSaga(),
    unLikeItemSaga(),
    getVideosSaga(),
    createGroupSaga(),
    showGalleryPostSaga(),
    handleFriendReqSaga(),
    getFriendRequestListSaga(),
    getUserPhotosSaga(),
    getUserAlbumsSaga(),
    getUserAlbumMediaSaga(),
    getUserVideosSaga(),
    uploadUserAlbumSaga(),
    uploadUserPhotoSaga(),
    uploadUserVideoSaga(),
    ResendOtpSaga(),
    walletSignUpSaga(),
    walletSignInSaga(),
    walletDataSaga(),
    walletPreviewDataSaga(),
    walletAddItemSaga(),
    deleteWalletSaga(),
    updateWalletItemSaga(),
    joinedRoomsSaga(),
    myRoomsSaga(),
    showRoomSaga(),
    leaveRoomSaga(),
    createRoomSaga(),
    addMemberSaga(),
    roomMembersSaga(),
    fetchAlbumsDataSaga(),
    deletePhotoSaga(),
    getRoomsVideosSaga(),
    updateRoomSaga(),
    previewAlbumSaga(),
    deleteAlbumSaga(),
    deleteAlbumPhotoSaga(),
    makeAdminSaga(),
    removeAdminSaga(),
    makeSilentObserverSaga(),
    removeSilentObserverSaga(),
    removeMemberSaga(),
    uploadAlbumSaga(),
    uploadAlbumImageSaga(),
    uploadAlbumVideoSaga(),
    deleteRoomRequestSaga(),
    deleteVideoSaga(),

    //Reels
    fetchReelsSaga(),
    // fetchUserReelsSaga(),
    uploadReelSaga(),
    updatedReelSaga(),
    deleteReelSaga(),
    reactToggleSaga(),
    increaseReelViewCountSaga(),
    fetchReelsCommentsSaga(),

    //Birthday
    fetchBirthdayDataSaga(),
    WishBirthdaySaga(),

    //BuyNsellSaga
    exploreBuyNsellReqSaga(),
    parentCategoryBuyNsellReqSaga(),
  ]);
}
