export const IMAGES = {
  aboutUser: require("../Assets/images/aboutUs.png"),
  add: require("../Assets/images/addIcon.png"),
  blockUsers: require("../Assets/images/blockUser.png"),
  blankDP: require("../Assets/images/blankDP.jpg"),
  changePassword: require("../Assets/images/changePassword.png"),
  camera: require("../Assets/images/camera.png"),
  deleteUser: require("../Assets/images/deleteUser.png"),
  deleteButton: require("../Assets/images/deleteButton.png"),
  dice: require("../Assets/images/dice.png"),
  downArrow: require("../Assets/images/downArrow.png"),
  edit: require("../Assets/images/editButton.png"),
  leftArrow: require("../Assets/images/leftArrow.png"),
  rightArrow: require("../Assets/images/right-arrow.png"),
  general: require("../Assets/images/general.png"),
  logout: require("../Assets/images/logout.png"),
  privacy: require("../Assets/images/privacy.png"),
  preferences: require("../Assets/images/preferences.png"),
  privacyPolicy: require("../Assets/images/privacyPolicy.png"),
  people: require("../Assets/images/people.png"),
  security: require("../Assets/images/security.png"),
  tagging: require("../Assets/images/tag.png"),
  termsAndCondition: require("../Assets/images/termsAndCondition.png"),
  userAvatar: require("../Assets/images/avatar.png"),
  userInfo: require("../Assets/images/userInfo.png"),
  pdfFile: require("../Assets/images/pdfFile.png"),
  wordFile: require("../Assets/images/wordFile.png"),
  bluePlusCircle: require("../Assets/images/bluePlusCircle.png"),
  standard: require("../Assets/images/standard.png"),
  loggedInDevices: require("../Assets/images/loggedInDevices.png"),
  houseOfCards: require("../Assets/images/houseOfCards.png"),
  blankCover: require("../Assets/images/blankCover.png"),
  walletCover: require("../Assets/images/walletCover.png"),
  userIDCard: require("../Assets/images/userIDCard.png"),
  graduationHat: require("../Assets/images/graduationHat.png"),
  portfolio: require("../Assets/images/portfolio.png"),
  oval: require("../Assets/images/oval.png"),
  illustration: require("../Assets/images/illustration.png"),
  vectorPlusIcon: require("../Assets/images/vectorPlusIcon.png"),
  friendRequest: require("../Assets/images/friendRequest.png"),
  searchNotFound: require("../Assets/images/searchNotFound.png"),
  backIcon: require("../Assets/images/backIcon.png"),
  userTag: require("../Assets/images/userTag.png"),
  smile: require("../Assets/images/smile.png"),
  map: require("../Assets/images/map.png"),
  postsColored: require("../Assets/images/postsColored.png"),
  job: require("../Assets/images/job.png"),
  expiry_timeIcon: require("../Assets/images/setExpirIcon.png"),
  appleIcon: require("../Assets/images/appleIcon.png"),
  appleIcon1: require("../Assets/images/apple_logo.png"),
  appleIcon2: require("../Assets/images/appleIcons.png"),
  appleIcon3: require("../Assets/images/apple_Icons.jpeg"),
  grid: require("../Assets/images/grid.png"),
  tiles: require("../Assets/images/tiles.png"),
  roomsMain: require("../Assets/images/rooms.png"),
  location: require("../Assets/images/location.png"),
  calender: require("../Assets/images/calender.png"),
  clock: require("../Assets/images/clock.png"),
  file: require("../Assets/images/file.png"),

  // Logo
  logo: require("../Assets/images/palsomeLogo.png"),
  palsomeLogo: require("../Assets/images/logo.png"),

  //Gifs & Pngs
  like_gif: require("../Assets/images/likegif.gif"),
  like_static: require("../Assets/images/ic_like.png"),
  like_static_fill: require("../Assets/images/ic_like_fill.png"),
  love_gif: require("../Assets/images/lovegif.gif"),
  love_static: require("../Assets/images/love2.png"),
  haha_gif: require("../Assets/images/hahagif.gif"),
  haha_static: require("../Assets/images/haha2.png"),
  wow_gif: require("../Assets/images/wowgif.gif"),
  wow_static: require("../Assets/images/wow2.png"),
  sad_gif: require("../Assets/images/sadgif.gif"),
  sad_static: require("../Assets/images/sad2.png"),
  angry_gif: require("../Assets/images/angrygif.gif"),
  angry_static: require("../Assets/images/angry2.png"),

  //Social Icons
  facebookICON: require("../Assets/images/facebookIcon.png"),
  googleICON: require("../Assets/images/googleIcon.png"),

  //Rooms
  room1: require("../Assets/images/room1.png"),
  room2: require("../Assets/images/room2.png"),
  room3: require("../Assets/images/room3.png"),
  room4: require("../Assets/images/room4.png"),
  room5: require("../Assets/images/room5.png"),
  room6: require("../Assets/images/room6.png"),

  // buyNsell
  buyNsell: require("../Assets/images/buyNsell.png"),
  filterBy: require("../Assets/images/filterBy.png"),
  searchIcon: require("../Assets/images/searchIcon.png"),
  uploadPhotoIcon: require("../Assets/images/uploadPhotoIcon.png"),
  crossIcon: require("../Assets/images/crossIcon.png"),
  addUploadIcon: require("../Assets/images/addUpLoadIcon.png"),
  buyNsellAd: require("../Assets/images/buyNsellAd.png"),
  buyNsellDotedMenu: require("../Assets/images/dotedMenu.png"),
  buyNsellHeartNotLike: require("../Assets/images/buyNsellHeartNotLike.png"),
  buyNsellHeartLikeGrid: require("../Assets/images/buyNsellHeartLikeGrid.png"),
  buyNsellHeartLikeTiles: require("../Assets/images/buyNsellHeartLikeTiles.png"),

  buyNsellCategoriesArrow: require("../Assets/images/buyNsellCategoriesArrow.png"),

  // Profile Screen
  clips: require("../Assets/images/clips.png"),
  group: require("../Assets/images/group.png"),
  groupDark: require("../Assets/images/groups_dark.png"),
  birthday: require("../Assets/images/birthday.png"),
  events: require("../Assets/images/events.png"),
  marketPlace: require("../Assets/images/marketPlace.png"),
  pages: require("../Assets/images/pages.png"),
  rooms: require("../Assets/images/rooms.png"),
  palsomeAI: require("../Assets/images/palsome_ai.png"),
  syncUser: require("../Assets/images/syncUser.png"),
  switchUserDropDown: require("../Assets/images/switchUserDropDown.png"),

  //Emojies Face
  angryEmoji: require("../Assets/images/angryEmoji.png"),
  annoyedEmoji: require("../Assets/images/annoyedEmoji.png"),
  confusedEmoji: require("../Assets/images/confusedEmoji.png"),
  confoundedEmoji: require("../Assets/images/confoundedEmoji.png"),
  crazyEmoji: require("../Assets/images/crazyEmoji.png"),
  happyEmoji: require("../Assets/images/happyEmoji.png"),
  loveEmoji: require("../Assets/images/loveEmoji.png"),
  satisfiedEmoji: require("../Assets/images/satisfiedEmoji.png"),
  strongEmoji: require("../Assets/images/strongEmoji.png"),
  sadEmoji: require("../Assets/images/sadEmoji.png"),
  sleepyEmoji: require("../Assets/images/sleepyEmoji.png"),
  tiredEmoji: require("../Assets/images/tiredEmoji.png"),
  shockedEmoji: require("../Assets/images/shockedEmoji.png"),
  sad: require("../Assets/images/sad2.png"),
  sadEmoji: require("../Assets/images/sadEmoji.png"),
  worriedEmoji: require("../Assets/images/worriedEmoji.png"),

  //Other Emojis
  listeningEmoji: require("../Assets/images/listeningEmoji.png"),
  watchingEmoji: require("../Assets/images/watchingEmoji.png"),
  playingEmoji: require("../Assets/images/playingEmoji.png"),
  eatingEmoji: require("../Assets/images/eatingEmoji.png"),
  juiceEmoji: require("../Assets/images/juiceEmoji.png"),
  travelingEmoji: require("../Assets/images/travelingEmoji.png"),
  readingEmoji: require("../Assets/images/booksEmoji.png"),
  calendarEmoji: require("../Assets/images/calendarEmoji.png"),
  celebratingEmoji: require("../Assets/images/celebratingEmoji.png"),
  lookingForEmoji: require("../Assets/images/lookingForEmoji.png"),
  graduationCap: require("../Assets/images/graduationCap.png"),

  // dummy
  image1: require("../Assets/images/image1.jpg"),
  image2: require("../Assets/images/image2.jpg"),
  image3: require("../Assets/images/image3.jpg"),
  image4: require("../Assets/images/image4.jpg"),
  image5: require("../Assets/images/image5.jpg"),
  image6: require("../Assets/images/image6.jpg"),

  //Clip
  clipLike: require("../Assets/images/clipLike.png"),
  clipUnlike: require("../Assets/images/clipUnlike.png"),
  clipShare: require("../Assets/images/clipShare.png"),
  clipComment: require("../Assets/images/clipComment.png"),

  // Reminder
  reminderCross: require("../Assets/images/reminderCross.png"),

  //
  touchBase: require("../Assets/images/touchbase.png"),
};
