export enum ColorSet {
  transparent = 'transparent',
  red = '#EC3D40',
  redcolor = '#FF3C4D',
  theme = '#517DD5',
  softSeaGreen = '#E5F4F7',
  softWhite = '#FBFDFF',
  secondary = '#E6E6E6',
  softGray = '#F5F5F5',
  softMidGray = '#E2E4E5',
  MidGray = '#A0AFB9',
  softBlue = '#F5F9FF',
  softGraySecondary = '#EAEFF5',
  grayLight = '#A1ADB3',
  grayMedium = '#5B676A',
  grayMidLight = '#8692A6',
  grayPaginationDots = '#D4DCE7',
  grayBorderColor = '#D4DCE7',
  inputText = '#ABABAB',
  inputBorderColor = '#E9E9E9',
  greenMid = '#93CC8E',
  greenLight = '#E5FCE3',
  white = '#FFFFFF',
  black = '#000000',
  black1 = '#101010',
  textBase = '#2E3B57',
  gradientLayout = "'#2B3B59', '#5C8D8A'",
  inputActiveBg = '#446572',
  
  brandColor = '#FD2101',
  
  selectingBrandColor = '#3BBA2D',
  
  blackColor = '#101010',
  softYellow = '#FFF6D4',
  border = '',

  seagreen = '#00A6B0',
  lightSeagreen = '#BDFBFF',
  yellowDark = '#FDB913',
  lightYellow = '#FFF6D4',
  green = '#00B091',
  lightGreen = '#DFFFE4',
  bluelight = '#DCE5F7',
  lightGraish = '#F5FAFF',
  blue = '#517dff'
}
