import { StyleSheet } from "react-native";
import { getHeight, getWidth } from "../../../Utils/NewResponsive";
import { HP, WP } from "../../../Utils/Resposive";
import { COLORS } from "../../Constants/Colors";
import { WidthScreen } from "../TopBar/Dimensions";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // marginVertical: 10,
    backgroundColor: COLORS.white,
    paddingVertical: 10,
  },
  backgroundVideo: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  ModelContanier: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  flatlistcontainer: {
    flexDirection: "row",
    marginHorizontal: 10,
    marginVertical: 7,
    justifyContent: "space-between",
  },
  headerTextEdit: {
    alignSelf: "center",
    fontWeight: "bold",
    fontSize: 18,
    left: getWidth(25),
  },
  flatlistInnerCont: {
    flexDirection: "row",
    marginHorizontal: 10,
    marginVertical: 7,
  },
  fullbtnEdit: {
    width: getWidth(20),
    height: getHeight(5),
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 5,
    marginRight: 5,
  },
  fullbtnTextEdit: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  btnmainEdit: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginRight: getWidth(3),
    marginTop: getHeight(1.5),
  },
  txtInputEdit: {
    backgroundColor: COLORS.cocoGrey,
    width: "95%",
    height: "30%",
    maxHeight: getHeight(30),
    minHeight: getHeight(20),
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 20,
  },
  headerEdit: {
    flexDirection: "row",
    backgroundColor: "white",
    alignItems: "center",
    height: getHeight(7),
    marginBottom: getHeight(2),
    borderBottomWidth: 0.5,
  },
  footer2: {
    paddingHorizontal: 10,
    backgroundColor: "white",
    left: 0,
    right: 0,
    height: 50,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopColor: COLORS.cocoGrey,
    flexDirection: "row",
  },
  txtInput: {
    height: 40,
    backgroundColor: COLORS.cocoGrey,
    width: "80%",
    borderRadius: 20,
  },
  img: {
    height: 130,
    width: 100,
    borderWidth: 1,
    borderRadius: 20,
    alignSelf: "center",
  },
  imgContainer: {
    borderTopWidth: 1,
    borderTopColor: "Gray",
    height: 150,
    width: WidthScreen,
    justifyContent: "flex-start",
    borderRadius: 10,
    paddingLeft: 10,
    flexDirection: "row",
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomContainer: {
    backgroundColor: COLORS.cocoGrey,
    borderRadius: 15,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 5,
    flexDirection: "row",
  },
  footer: {
    position: "absolute",
    backgroundColor: "white",
    left: 0,
    right: 0,
    height: 50,
    bottom: 0,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: COLORS.cocoGrey,
    flexDirection: "row",
  },
  header: {
    borderBottomColor: COLORS.cocoGrey,
    borderBottomWidth: 1,
    height: 50,
    justifyContent: "space-between",
    flexDirection: "row",

    alignItems: "center",
  },
  sharePost: {
    borderWidth: 0.5,
    borderColor: COLORS.cocoGrey,
    marginHorizontal: 15,
    marginBottom: 10,
    paddingVertical: 10,
  },
  upperTab: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 17,
    paddingBottom: 8,
  },
  dp: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  name: {
    fontSize: 16,
    color: COLORS.primary,
    marginLeft: 10,
    fontWeight: "bold",
  },
  action: {
    color: COLORS.lightGray,
    marginLeft: 10,
    flexGrow: 1,
  },
  time: {
    color: COLORS.black,
    marginLeft: 10,
  },
  privacyTagContainer: {
    width: 25,
    height: 25,
    marginTop: 3,
  },

  feeling_action: { color: COLORS.lightGray, marginTop: HP(0.5) },
  feeling_value: {
    fontWeight: "bold",
    color: COLORS.darkGray,
    marginTop: HP(0.5),
  },
  image: {
    flex: 1,
    justifyContent: "center",
    width: WP(100),
    marginLeft: -WP(2.1),
    height: HP(45),
  },
  text: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,
    height: WP(45),
    justifyContent: "center",
    alignItems: "center",
  },
  colorPost: {
    flex: 1,
    justifyContent: "center",
    // width: WP(90),
    minHeight: HP(40),
  },
  imgAndStatus: {
    flexDirection: "row",
  },
  tagTxt: {
    marginLeft: 8,
    textDecorationLine: "underline",
    color: COLORS.primary,
  },
  singlePostStyle: {
    // alignItems: "center",
    // paddingTop: 10,
  },
  postedView: {
    height: HP(50),
  },
  imageShare: {
    height: HP(50),
    alignItems: "center",
    justifyContent: "center",
  },
  noContent: {
    borderWidth: 0.5,
    borderColor: COLORS.cocoGrey,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 15,
    marginBottom: 10,
    paddingVertical: 10,
  },
});
export default styles;
