import { StyleSheet } from "react-native";
import { getFontSize, getHeight, getWidth } from "../../../Utils/NewResponsive";
import { HP, WP } from "../../../Utils/Resposive";
import { WidthScreen } from "../../Components/TopBar/Dimensions";
import { COLORS } from "../../Constants/Colors";

const timelineStyles = StyleSheet.create({
  container: { flex: 1 },
  loading: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: COLORS.primary,
    flex: 0.08,
  },
  creating: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: COLORS.primary,
    flex: 0.08,
  },
  userNameContainer: {
    width: getWidth(100),
    height: getHeight(5.5),
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    margin: 5,
  },
  arrowLeftContainer: {
    width: getWidth(15),
    alignItems: "center",
    justifyContent: "center",
  },
  userNameText: {
    fontSize: getFontSize(2.5),
    fontWeight: "bold",
    alignSelf: "center",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 20,
    maxWidth: getWidth(80), // Set a maximum width for the text
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  txt: {
    color: COLORS.white,
  },
  coverPhoto: {
    height: HP(22),
    width: WidthScreen,
    borderBottomWidth: 3,
    borderColor: COLORS.white,
  },
  otherImg: {
    marginTop: HP(1),
    justifyContent: "center",
    alignItems: "center",
  },
  upperTab: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // paddingHorizontal: 17,
    paddingBottom: 8,
    width: "105%",
    backgroundColor: COLORS.red,
  },
  imgAndStatus: {
    flexDirection: "row",
  },
  image: {
    flex: 1,
    justifyContent: "center",
    width: WP(100),
    height: HP(45),
  },
  imageShared: {
    flex: 1,
    justifyContent: "center",
    // width: WP(82),
    height: HP(45),
  },
  dpContainer: {
    borderRadius: 200,
    alignSelf: "center",
    justifyContent: "center",
  },
  profileImag: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  dp: {
    borderWidth: 5,
    alignSelf: "center",
    borderRadius: 340,
    width: 150,
    height: 150,
    borderColor: "white",
  },
  profileCamera: {
    backgroundColor: COLORS.darkGray,
    height: getHeight(6),
    width: getHeight(6),
    borderRadius: 30,
    position: "absolute",
    right: -2,
    justifyContent: "center",
    bottom: getHeight(-1),
  },
  coverCamera: {
    backgroundColor: COLORS.darkGray,
    height: getHeight(6),
    width: getHeight(6),
    borderRadius: 30,
    position: "absolute",
    right: getWidth(2),
    top: getHeight(14),
    justifyContent: "center",
  },
  time: {
    color: COLORS.black,
    marginLeft: 10,
    paddingRight: 5,
  },
  tagTxt: {
    left: getWidth(2.5),
    textDecorationLine: "underline",
    color: COLORS.primary,
  },
  name: {
    fontSize: 15,
    color: COLORS.primary,
    marginLeft: 10,
    fontWeight: "bold",
  },
  action: {
    color: COLORS.lightGray,
    marginLeft: 5,
  },
  userName: {
    // height: HP(7),
    paddingTop: 12,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  timelineContainer: {
    flex: 1,
    marginVertical: 9,
    marginHorizontal: 10,
    marginRight: 24,
  },
  usertext: { fontSize: 24, fontWeight: "bold" },
  btn: {
    // width: getWidth(35),
    // height: getHeight(5),
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    paddingHorizontal: getWidth(4),
    paddingVertical: getWidth(2),
    marginVertical: getHeight(0.5),
  },
  timelineDp: {
    width: 50,
    height: 50,
    borderRadius: 50,
    margin: 5,
  },
  btnText: {
    color: "white",
    fontSize: 14,
  },
  btncontaner: {
    // height: HP(8),
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    marginVertical: getHeight(1),
  },
  iconStyle: {
    color: "white",
    // fontSize: 18,
    marginRight: getWidth(2),
  },
  aboutProfile: {
    // height: HP(25),
    alignItems: "center",
    justifyContent: "space-around",
    // paddingVertical: getHeight(5),
  },
  fullbtn: {
    width: getWidth(80),
    height: getHeight(5.5),
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 5,
    marginVertical: 10,
  },
  fullbtnText: {
    color: "white",
    fontSize: 16,
  },
  friendsList: {
    backgroundColor: "red",
    flex: 0.9,
  },
  friendContainer: {
    justifyContent: "space-between",
    paddingHorizontal: getWidth(3),
    flexDirection: "row",
    marginVertical: 10,
  },
  fbtn: {
    // width: getWidth(20),
    backgroundColor: COLORS.primary,
    // height: getHeight(5),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    paddingHorizontal: WP(2),
  },
  friendFlatlist: {
    // paddingHorizontal: 4,
    flex: 1,
    marginLeft: 5,
  },
  timelineFlatlist: {
    // paddingHorizontal: 4,
    flex: 1,
  },
  ItemSeparator: {
    height: 13,
  },
  friend: {
    width: getWidth(30),

    // height: getHeight(20),
    marginHorizontal: 5,
  },
  friendImg: {
    height: getHeight(15),
    width: getWidth(30),
    borderRadius: 13,
  },
  text: {
    justifyContent: "center",
    alignSelf: "center",
    fontSize: 15,
    fontWeight: "bold",
    marginTop: 5,
  },
  colorPost: {
    flex: 1,
    justifyContent: "center",
    width: WP(100),
    height: HP(40),
  },
  colorPostShared: {
    flex: 1,
    justifyContent: "center",
    // width: WP(94.4),
    height: HP(40),
  },
  noPostsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    width: "80%",
    alignSelf: "center",
    marginVertical: 15,
    padding: 10,
    borderRadius: 10,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 8,
  },
  mapaction: {
    color: COLORS.lightGray,
    marginLeft: 5,
    fontWeight: "bold",
  },
  psted_text: { paddingBottom: 7, paddingHorizontal: 16, paddingLeft: 0 },

  backButtonWrapper: {
    // backgroundColor: COLORS.darkGray,
    height: getHeight(5),
    width: getHeight(8),
    borderRadius: getHeight(0),
    // marginLeft: WP(2),
    // marginTop: getHeight(2),
    justifyContent: "center",
    // alignItems: "center",
    // position: "absolute",
    // zIndex: 1000,
    // left: -85,
    // right: 100,
    paddingLeft: 5,
  },
  tabBullet: {
    padding: WP(3),
    borderRadius: WP(6),
    marginHorizontal: WP(2.2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.tooLightGrey,
  },
  tabBulletTxt: {
    fontWeight: "bold",
    color: "black",
  },
  BulletContainer: { marginVertical: 10 },
  noContent: {
    borderWidth: 0.5,
    borderColor: COLORS.cocoGrey,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 15,
    marginBottom: 10,
    paddingVertical: 10,
  },
});
export default timelineStyles;
